# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Max Learning FI
name: Max Learning FI
email: fi@xk.io
description: >- # this means to ignore newlines until "baseurl:"
  Max Learning FI, Tutorials with Curi: notes and things from June 2020 onwards. Topics include: grammar, overreaching, The Choice by Eli Goldratt,
  and other things.
baseurl: "/fi" # the subpath of your site, e.g. /blog
url: "https://xertrov.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: xertrov
github_username:  xertrov

future: true
# encoding: binmode

permalink: pretty
exclude: ["node_modules/", "**/tex/*", "tex/", "*.tex", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

aux_links:
  "feed.xml":
    - "/fi/feed.xml"
  "Public Docs":
    - "https://drive.google.com/drive/u/0/folders/1_CXXYqdyV8FE5BWXMGChlhd76vL4gc--"
  "YouTube":
    - "https://www.youtube.com/channel/UCscXO9PxvE7M2YZQmJo6LwA"
  "Tutoring Playlist":
    - "https://www.youtube.com/playlist?list=PLKx6lO5RmaetREa9-jt2T-qX9XO2SD0l2"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

collections_order:
  - posts
  - tutorials
  - analyzing_lies
  - pub_drafts
  - books
  - grammar_exercises
  - notes
  - flux

collections:
  pub_drafts:
    title: Public Drafts
    output: true
    permalink: /pub-drafts/:name/
    priority: 30
  books:
    title: Books
    output: true
    permalink: /books/:name/
    priority: 40
  tutorials:
    title: Tutorials with Elliot
    output: true
    permalink: /notes/:name/
    sort_by: lesson
    priority: 20
  grammar_exercises:
    title: Grammar Exercises
    output: true
    permalink: /ex-parsing/:name/
    priority: 50
  flux:
    title: Flux
    output: true
    permalink: /flux/:name/
    priority: 90
  posts:
    title: Posts
    output: true
    permalink: /posts/:name/
    priority: 10
  notes:
    title: Notes
    output: true
    permalink: /notes/:name/
    priority: 70
  analyzing_lies:
    title: Analyzing Lies
    output: true
    permalink: /analyzing-lies/:name/
    priority: 25

# Sort order for navigation links
nav_sort: case_insensitive # default, equivalent to nil
# nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content
footer_content: ""

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"


talkyard_server_url: https://comments-for-xk-io.talkyard.net
talkyard_script_url: https://c1.ty-cdn.net/-/talkyard-comments.min.js


plugins:
    - jekyll-redirect-from
#   - jekyll-feed
#   - jekyll-remote-theme
# remote_theme: pmarsceill/just-the-docs
color_scheme: nil # "dark"
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/xertrov/fi" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
gh_raw_repository: "https://raw.githubusercontent.com/XertroV/fi"
gh_raw_link_text: "View Raw File"

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

compress_html:
  clippings: false # all
  comments: false # all
  endings: false # all
  startings: []
  blanklines: false
  profile: false

# defaults:
#   - scope:
#       path: "*.md"
#     values:
#       layout: "page"
